In [1]:
import pandas as pd

In [2]:
df_pf = pd.read_csv('../dados/PF_tratados.csv')
df_pf.head()

,ID Cliente,Linha de Ação,Produto GPOM,Data de Venda,Classe de Serviço,Data de Nascimento,Gênero,Cidade,Microrregião,Estado,Fim de Vigência,Tipo Pessoa,Área de Atuação,Área de Atuação e Produto GPOM,Idade,Tempo de Contrato,Longitude,Latitude
0,56943,EDUCACAO,COLEGIO SESI NOVO ENSINO MEDIO,2022-10-28,ENSINO MEDIO – ITINERARIOS,2008-05-16,MASCULINO,CURITIBA,CURITIBA,PR,2023-12-15,FÍSICA,NÃO INFORMADO,COLEGIO SESI NOVO ENSINO MEDIO / NÃO INFORMADO,14,413,-49.264622,-25.419547
1,19906,EDUCACAO,EDUCACAO INFANTIL,2023-01-13,EDUCACAO INFANTIL - PRE-ESCOLA,1981-08-13,FEMININO,CURITIBA,CURITIBA,PR,2023-12-25,FÍSICA,NÃO INFORMADO,EDUCACAO INFANTIL / NÃO INFORMADO,41,346,-49.264622,-25.419547
2,19906,EDUCACAO,ENSINO FUNDAMENTAL INTERNACIONAL,2021-10-07,ENSINO FUNDAMENTAL - 1º AO 5º ANO,1981-08-13,FEMININO,CURITIBA,CURITIBA,PR,2022-12-14,FÍSICA,NÃO INFORMADO,ENSINO FUNDAMENTAL INTERNACIONAL / NÃO INFORMADO,40,433,-49.264622,-25.419547
3,19906,EDUCACAO,ENSINO FUNDAMENTAL INTERNACIONAL,2023-01-13,ENSINO FUNDAMENTAL - 1º AO 5º ANO,1981-08-13,FEMININO,CURITIBA,CURITIBA,PR,2023-12-25,FÍSICA,NÃO INFORMADO,ENSINO FUNDAMENTAL INTERNACIONAL / NÃO INFORMADO,41,346,-49.264622,-25.419547
4,6940,EDUCACAO,COLEGIO SESI INTERNACIONAL,2021-10-14,ENSINO MEDIO,2006-11-01,FEMININO,CURITIBA,CURITIBA,PR,2022-12-14,FÍSICA,NÃO INFORMADO,COLEGIO SESI INTERNACIONAL / NÃO INFORMADO,14,426,-49.264622,-25.419547

In [3]:
transacao = []

for cliente_id in df_pf['ID Cliente'].unique():
    # Obter todas as transações do cliente
    transacoes_cliente = df_pf[df_pf['ID Cliente'] == cliente_id]
    
    # Agregar transações por produto e data de nascimento
    transacoes_agrupadas = transacoes_cliente.groupby(['Produto GPOM', 'Data de Nascimento']).size().reset_index(name='count')
    
    # Criar uma lista de produtos únicos por cliente
    lista_produtos = list(transacoes_agrupadas['Produto GPOM'])
    
    # Adicionar lista de produtos únicos à lista de transações
    transacao.append(lista_produtos)

In [4]:
transacao[0:5]

[['COLEGIO SESI NOVO ENSINO MEDIO',
  'QUALIFICACAO PROFISSIONAL',
  'QUALIFICACAO PROFISSIONAL'],
 ['EDUCACAO INFANTIL',
  'ENSINO FUNDAMENTAL INTERNACIONAL',
  'GRADUACAO',
  'QUALIFICACAO PROFISSIONAL',
  'TECNICO DE NIVEL MEDIO',
  'TECNICO DE NIVEL MEDIO'],
 ['APERFEICOAMENTO PROFISSIONAL',
  'APERFEICOAMENTO PROFISSIONAL',
  'COLEGIO SESI',
  'COLEGIO SESI INTERNACIONAL',
  'COLEGIO SESI NOVO ENSINO MEDIO',
  'EDUCACAO CONTINUADA',
  'EDUCACAO CONTINUADA',
  'GRADUACAO',
  'GRADUACAO',
  'TECNICO DE NIVEL MEDIO'],
 ['APERFEICOAMENTO PROFISSIONAL',
  'APERFEICOAMENTO PROFISSIONAL',
  'COLEGIO SESI NOVO ENSINO MEDIO',
  'QUALIFICACAO PROFISSIONAL',
  'TECNICO DE NIVEL MEDIO',
  'TECNICO DE NIVEL MEDIO',
  'TECNICO DE NIVEL MEDIO',
  'TECNICO DE NIVEL MEDIO'],
 ['COLEGIO SESI INTERNACIONAL',
  'COLEGIO SESI NOVO ENSINO MEDIO',
  'TECNICO DE NIVEL MEDIO']]

## Algoritmo Apriori

### Aplicando a regra de associação

In [5]:
%pip install mlxtend

Requirement already satisfied: mlxtend in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (0.23.1)
Requirement already satisfied: scipy>=1.2.1 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from mlxtend) (1.12.0)
Requirement already satisfied: numpy>=1.16.2 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from mlxtend) (2.1.4)
Requirement already satisfied: scikit-learn>=1.0.2 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from mlxtend) (1.3.0)
Requirement already satisfied: matplotlib>=3.0.0 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from mlxtend) (3.8.0)
Requirement already satisfied: joblib>=0.13.2 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from mlxtend) (1.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in /home/ba/anaconda3/envs/senai-env/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
from mlxtend.preprocessing import TransactionEncoder

In [7]:
te = TransactionEncoder() # estanciar função
transacao_te = te.fit(transacao).transform(transacao)

In [8]:
transacao_te

array([[False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False, False],
       [False,  True, False, ...,  True, False, False],
       ...,
       [False, False, False, ...,  True, False, False],
       [False, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False]])

In [9]:
# transformar em dataframe
transacao_transformado = pd.DataFrame(transacao_te, columns=te.columns_)
transacao_transformado

,ACADEMIA SESI,APERFEICOAMENTO PROFISSIONAL,APERFEICOAMENTO PROFISSIONAL - ACOES MOVEIS,APERFEICOAMENTO PROFISSIONAL - E-COMMERCE,ATIVIDADES LIVRES,AUXILIO DIAGNOSTICO,CARTAO VIVA +,COLEGIO SESI,COLEGIO SESI INTERNACIONAL,COLEGIO SESI INTERNACIONAL TRILINGUE,...,LAUDOS,METROLOGIA,NAO SE APLICA,POS-GRADUACAO,PROGRAMAS DE SAUDE E SEGURANCA,QUALIFICACAO PROFISSIONAL,QUALIFICACAO PROFISSIONAL - ACOES MOVEIS,TECNICO DE NIVEL MEDIO,TESTAGEM COVID IMUNOLOGICO,VACINACAO
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
2,False,True,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,True,False,False
3,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13883,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13884,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13885,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
13886,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
13887,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [10]:
# algoritmo apriori
from mlxtend.frequent_patterns import apriori

In [11]:
items_frequentes_apriori = apriori(transacao_transformado, use_colnames=True, min_support=0.02)
items_frequentes_apriori.sort_values(['support'],ascending=False)

      support                                           itemsets
12   0.642425                           (TECNICO DE NIVEL MEDIO)
0    0.433324                     (APERFEICOAMENTO PROFISSIONAL)
11   0.368304                        (QUALIFICACAO PROFISSIONAL)
19   0.277362  (TECNICO DE NIVEL MEDIO, APERFEICOAMENTO PROFI...
43   0.247336  (TECNICO DE NIVEL MEDIO, QUALIFICACAO PROFISSI...
..        ...                                                ...
102  0.020521  (TECNICO DE NIVEL MEDIO, COLEGIO SESI, GRADUAC...
54   0.020449  (EDUCACAO CONTINUADA, APERFEICOAMENTO PROFISSI...
95   0.020377  (APERFEICOAMENTO PROFISSIONAL, QUALIFICACAO PR...
81   0.020233  (EDUCACAO CONTINUADA, ENSINO FUNDAMENTAL INTER...
93   0.020089  (EDUCACAO CONTINUADA, APERFEICOAMENTO PROFISSI...

[109 rows x 2 columns]

In [12]:
from mlxtend.frequent_patterns import association_rules

regras_apriori = association_rules(items_frequentes_apriori, metric='confidence', min_threshold=0.2)
regras_apriori

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(APERFEICOAMENTO PROFISSIONAL),(COLEGIO SESI),0.433324,0.198013,0.099078,0.228647,1.154711,0.013275,1.039716,0.236435
1,(COLEGIO SESI),(APERFEICOAMENTO PROFISSIONAL),0.198013,0.433324,0.099078,0.500364,1.154711,0.013275,1.134177,0.167063
2,(APERFEICOAMENTO PROFISSIONAL),(COLEGIO SESI NOVO ENSINO MEDIO),0.433324,0.240927,0.117800,0.271851,1.128353,0.013400,1.042469,0.200736
3,(COLEGIO SESI NOVO ENSINO MEDIO),(APERFEICOAMENTO PROFISSIONAL),0.240927,0.433324,0.117800,0.488942,1.128353,0.013400,1.108830,0.149857
4,(EDUCACAO CONTINUADA),(APERFEICOAMENTO PROFISSIONAL),0.147537,0.433324,0.070997,0.481210,1.110510,0.007065,1.092304,0.116736
...,...,...,...,...,...,...,...,...,...,...
388,"(TECNICO DE NIVEL MEDIO, COLEGIO SESI, COLEGIO...","(APERFEICOAMENTO PROFISSIONAL, QUALIFICACAO PR...",0.060772,0.173963,0.020665,0.340047,1.954710,0.010093,1.251661,0.520017
389,"(TECNICO DE NIVEL MEDIO, COLEGIO SESI NOVO ENS...","(APERFEICOAMENTO PROFISSIONAL, COLEGIO SESI)",0.090366,0.099078,0.020665,0.228685,2.308126,0.011712,1.168034,0.623050
390,"(APERFEICOAMENTO PROFISSIONAL, COLEGIO SESI)","(TECNICO DE NIVEL MEDIO, COLEGIO SESI NOVO ENS...",0.099078,0.090366,0.020665,0.208576,2.308126,0.011712,1.149363,0.629076
391,"(COLEGIO SESI, QUALIFICACAO PROFISSIONAL)","(TECNICO DE NIVEL MEDIO, APERFEICOAMENTO PROFI...",0.090654,0.099006,0.020665,0.227959,2.302466,0.011690,1.167028,0.622077
392,"(COLEGIO SESI, COLEGIO SESI NOVO ENSINO MEDIO)","(TECNICO DE NIVEL MEDIO, APERFEICOAMENTO PROFI...",0.071213,0.136737,0.020665,0.290192,2.122269,0.010928,1.216193,0.569351

In [13]:
len(df_pf['ID Cliente'].unique())

13888

In [14]:
def recommend_items(customer_items, rules, min_confidence=0.6):
    """
    Função para recomendar itens com base nos itens comprados por um cliente
    e nas regras de associação geradas pelo algoritmo Apriori.
    """
    recommended_items = set()
    
    for _, regras_apriori in rules.iterrows():
        if set(regras_apriori['antecedents']).issubset(customer_items) and regras_apriori['confidence'] >= min_confidence:
            recommended_items.update(regras_apriori['consequents'])
    
    return recommended_items

In [15]:
itens_comprados = {'EDUCACAO CONTINUADA'}
recommend_items = recommend_items(itens_comprados, regras_apriori)
print("Tens recomendados:", recommend_items)

Tens recomendados: {'TECNICO DE NIVEL MEDIO'}